### ISSUE TITLE
This doesn't work anymore?

### ISSUE THREAD

**Issue by marklajer** [Ilshidur/LoL-item-sets-Mac#4] opened 2018-05-01 17:17 UTC
It's importing but not appearing in-game. If I try to import manually I get the following error:
<img width="408" alt="screen shot 2018-05-01 at 19 16 16" src="https://user-images.githubusercontent.com/4114961/39483935-4bf2c6c2-4d74-11e8-8fb5-ae909d4d4c2f.png">

**Comment by melchor629** [comment] 2018-05-01 20:34
It seems that the problem is not related to the macOS client. So I suggest you to fill the bug in [here](https://github.com/Ilshidur/feeder.lol-item-sets-generator.org/issues/new).

I tried the item sets and I get an error too, so maybe LoL has changed the format...

**Comment by Ilshidur** [comment] 2018-05-02 22:27
I am reopening this issue just to say that this is **fixed** ([details in this issue](https://github.com/league-of-legends-devs/feeder.lol-item-sets-generator.org/issues/34)).

Thank you @marklajer for your bug report. Feel free to report any bug by creating a new GitHub issue ;-)

Closing again.

**Closed as completed by Ilshidur** 2018-05-02 22:27 UTC
